<?php 
function merci_rule_rules_event_info() {
  return array(
    'example_rule_event' => array(
      'label' => t('Reservation refresh rule event'),
      'module' => 'Merci_rule',
      'group' => 'Merci Reservation Rule' ,
      'variables' => array(
        'current_user' => array('type' => 'user', 'label' => t('The current logged in user.')),
        'article' => array('type' => 'node', 'label' => t('The article node.')),
        'some_text' => array('type' => 'text', 'label' => t('Some arbitrary text.')),
      ),
    ),
  );
}